name: Blissedoutdesign
favicon: null
layout_spectrum: 0.6687209701631218
typography_spectrum: 0.19419422023929656
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.3097768274601549
  lightness: 0.1826771032065153
  saturation: 0.49846035870723426
  rhythmicContrast: 0.26353465858846903
purpose: []
